gestion_Stock/gestionCommande/urls.py
from django.urls import path

from .views import *




urlpatterns = [
    # ici on declare le view  qui sera definit dans view et le nom pour acceder a sa page template
    path("",home,name='acceuil'),
    path("about/",about,name='about'),
    path("produit/",list_produits,name='produit'),
    path("produit/<int:id>",detail_produits,name='details'),
    path("produit/new", new_product, name='nouveau_produit'),
    path("produit/search/", search, name='search_produit'),
    path("produit/edit_produit/<int:id>",edit_produit,name='edit_produit'),
    path("produit/delete_produit/<int:id>",delete_produit,name='delete_produit'),
    path("categories/",categories,name='categories'),
    path("categorie/<int:id>",parcategorie,name='typecategories'),
    path("client/new", new_client, name='client'),
    path("client/",client,name='list_client'),
    path("client/<int:id>",detail_clients,name='details_client'),
    path("client/delete_client/<int:id>", delete_client, name='delete_client'),
    path("produit/edit_client/<int:id>",edit_client,name='edit_client'),


]

gestion_Stock/gestionStock/urls.py
from django.contrib import admin
from django.urls import path, include

import gestionCommande
import  utilisateurs
import  panier


from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gestionCommande.urls')),
    path('', include('utilisateurs.urls')),
    path('', include('panier.urls')),

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

gestion_Stock/panier/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/', views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/',views.cart_detail,name='cart_detail'),
]

gestion_Stock/gestionCommande/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

from django.db import models



class Categorie(models.Model):
    designation = models.CharField(max_length=30)
    description = models.CharField(max_length=30,null=True,blank=True)

    def __str__(self):
        return  f"{self.designation} {self.description}"


class Produit(models.Model):
    designation = models.CharField(max_length=30)
    description = models.CharField(max_length=30,null=True)
    datePerempt = models.DateField()
    prixU = models.IntegerField()
    quantite = models.IntegerField()
    photo = models.ImageField(null=True, blank=True, upload_to='images/')
    #auteur = models.ForeignKey(User, on_delete=models.CASCADE)
    categorie = models.ForeignKey(Categorie, null=True, blank=True, on_delete=models.CASCADE)
    #archive = models.BooleanField(default=False)
    def __str__(self):
        return  f"{self.designation} {self.datePerempt} {self.prixU} {self.quantite}"

class Client(models.Model):
    nom = models.CharField(max_length=30)
    prenom = models.CharField(max_length=30)
    email = models.EmailField(max_length=30)
    telephone = models.CharField(max_length=15)
    adresse = models.CharField(max_length=30)



class Commande(models.Model):
    dateCommande = models.DateField()
    statut = models.BooleanField(max_length=25)
    details = models.ManyToManyField(Produit, through='DetailCommande')
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.dateCommande} {self.statut} {self.details}"



    def __str__(self):
        return  f"{self.nom} {self.prenom} {self.email} {self.telephone} {self.adresse}"

class DetailCommande(models.Model):
    quantite = models.IntegerField(default=1)
    commande = models.ForeignKey(Commande, on_delete=models.CASCADE)
    produit = models.ForeignKey(Produit, on_delete=models.CASCADE)

    def __str__(self):
        return  f"{self.quantite} {self.commande} {self.produit}"

class Compte(models.Model):
    login = models.CharField(max_length=25)
    password = models.CharField(max_length=25)
    status = models.CharField(max_length=7)

    def __str__(self):
        return  f"{self.login} {self.password} {self.status}"

class Facture(models.Model):
    commande = models.OneToOneField(Commande, on_delete=models.CASCADE)
    montant = models.IntegerField()
    date = models.DateField()

    def __str__(self):
        return  f"{self.commande} {self.montant} {self.date}"

gestion_Stock/gestionCommande/forms.py
from  django import  forms
from  django.contrib.auth.forms import  UserCreationForm
from  django.contrib.auth.models import  User

from gestionCommande.models import Client


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ('nom','prenom','email', 'telephone', 'adresse')
        # ou bien  fields= '__all__'
        widgets = {
            'nom': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'prenom': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'email': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'telephone': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'adresse': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
        }

gestion_Stock/gestionCommande/views.py
import os

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

# Create your views here.
from django.utils._os import safe_join

from gestionCommande.forms import ClientForm
from gestionCommande.models import Produit, Categorie ,Client
from django.conf import settings


@login_required(login_url="/login/")
def home(request):
    categories = Categorie.objects.all()
    context = {"categories": categories}
    print(context)
    produits = Produit.objects.all()
    context = {"produits": produits,"categories": categories}
    print(context)
    return  render(request ,"pages/index.html",context)

def about(request):
    message="Voici un variable de la vue qu'on affiche dans notre templates"
    context={"message":message}
    return  render(request ,"pages/about.html",context)

# on force l'utilisateur a se connecter d'abord pour acceder a cette page
@login_required(login_url="/login/")
def list_produits(request):
    user= request.user;
    print(user)
        #Pour les filtres ici seul l'utilisateur ne voit que ces donnees
           #produits = Produit.objects.filter(auteur=user)
        # Pour les filtres ici seul l'utilisateur ne voit que ces donnees dons si on voudrait l'appliquer on
        #  remplace all par filter et on passe l'objet auteur com auteur=user
    produits=Produit.objects.all()
    # Gestion de la pagination
    paginator = Paginator(produits, 8)  # Show 8 produits par page.
    page = request.GET.get('page')
    try:
        produits= paginator.page(page)
        context = {"produits": produits}
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        produits= paginator.page(1)
        context = {"produits": produits}
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        produits = paginator.page(paginator.num_pages)
        context = {"produits": produits}

    return render(request, "produits/produit.html",context)


@login_required(login_url="/login/")
def categories(request):
    # user = request.user;
    # print(user)
    # Pour les filtres ici seul l'utilisateur ne voit que ces donnees
    # produits = Produit.objects.filter(auteur=user)
    # Pour les filtres ici seul l'utilisateur ne voit que ces donnees dons si on voudrait l'appliquer on
    #  remplace all par filter et on passe l'objet auteur com auteur=user
    categories = Categorie.objects.all()
    context = {"categories":  categories}
    print(context)
    return render(request, "pages/index.html", {"categories":  categories})

@login_required(login_url="/login/")
def  parcategorie(request,id):
     categorie= get_object_or_404(Categorie,id=id)
     categorie = Categorie.objects.get(id=id)
     designation=categorie.designation
     print('voici la designation de',designation)

     produits = Produit.objects.filter(categorie_id=categorie.id)
     categories = Categorie.objects.all()
     context = {"produits": produits, "categories": categories}
     print(context)

     return render(request, "categories/categories.html",context)



@login_required(login_url="/login/")
def detail_produits(request,id):
    produit= get_object_or_404(Produit,id=id)
    context = {"produit": produit}
    print(context)
    return render(request, "produits/produit_detail.html",context)

@login_required(login_url="/login/")
def search(request):
    categories = Categorie.objects.all()
    query = request.GET.get('query')
    print(query)
    if not query:
        produits = Produit.objects.all()
    else :
        produits = Produit.objects.filter(designation__icontains=query)
        context = {"produits": produits}
        #print(context)
    return render(request, "produits/search.html", {"produits" : produits ,"categories": categories})

@login_required(login_url="/login/")
def  new_product(request):
    categories= Categorie.objects.all()
    produits= Produit.objects.all()
    if request.method == "POST" :
        form = Produit(request.POST, request.FILES)
        print("FILES", request.FILES)
        auteur = request.user
        print("auteur ",auteur)
        designation = request.POST['designation']
        description = request.POST['description']
        datePerempt = request.POST['datePerempt']
        prixU = request.POST['prixU']
        quantite = request.POST['quantite']
        photo = request.FILES['photo']
        nom_categorie= request.POST['categorie']
        categorie=Categorie.objects.get(designation=nom_categorie)
        produit= Produit.objects.create(
            designation =designation,
            description =description,
            datePerempt =datePerempt,
            prixU =prixU,
            quantite = quantite,
            photo = photo,
            categorie=  categorie
        )
        context={'categorie':categorie}
        produit.save()
        return render(request,'produits/produit.html',locals())

    return render(request, "produits/nouveau_produit.html",{'categories':categories})




@login_required(login_url="/login/")
def  edit_produit(request,id):
    produit = get_object_or_404(Produit,id=id)
    if request.method == "POST" :
        request.POST, request.FILES

        designation = request.POST['designation']
        description = request.POST['description']
        datePerempt = request.POST['datePerempt']
        prixU = request.POST['prixU']
        print("Voici le prix Unitaire =",  prixU)
        quantite = request.POST['quantite']
        print("Voici la quantitee est =", quantite)
        photo = request.FILES['photo']
        #new_path = settings.MEDIA_ROOT + photo
        print("poiuytrewwertyuioiuytrewu",type(photo))
        #path1 = safe_join(os.path.abspath(settings.MEDIA_ROOT) + '\images', photo)
        #print(path1)
        print("Voici la photo",photo)

        print("type  poiuytre",type(produit.photo.url))
        #print("Deuxieme voici ureal de la page", photo.url)
        produit_to_update= Produit.objects.filter(pk=produit.id)
        produit_to_update.update(
            designation =designation,
            description =description,
            datePerempt =datePerempt,
            prixU =prixU,
            quantite = quantite,
            photo = photo
        )
        print("photo",photo)
        print("Derniere affichage url de la page", produit.photo.url)
        return  redirect("/produit")


    return render(request, "produits/edit_produit.html",{"produit" : produit})



@login_required(login_url="/login/")
def  delete_produit(request,id):
    produit = get_object_or_404(Produit,id=id)
    if request.method == "POST" :
        produit.delete()
        return  redirect("/")


    return render(request, "produits/delete_produit.html",{"produit" : produit})


def new_client(request):
        if request.method == "POST":
            clientform = ClientForm(request.POST)
            if clientform.is_valid():
                clientform.save()
                return redirect("/client")
        else:
            clientform = ClientForm()
        return render(request, "clients/new_client.html", {"form":  clientform})


def client(request):
    clients = Client.objects.all()
    context = {"clients":  clients}
    # print(context)
    return render(request, "clients/clients.html",{"clients":  clients} )

def detail_clients(request,id):
    client= get_object_or_404(Client,id=id)
    context = {"client":  client}
    print(context)
    print('voici le nom du client bla bla bla',client.nom)
    return render(request, "clients/client_detail.html",context)

def  delete_client(request,id):
    client = get_object_or_404(Client,id=id)
    if request.method == "POST" :
        client.delete()
        return  redirect("/")
    return render(request, "clients/delete_client.html", {"client": client})

def edit_client(request, id):
    client = get_object_or_404(Client, id=id)
    clientform = ClientForm(request.POST)
    if request.method == "POST":
            clientform = ClientForm(request.POST)

            if clientform.is_valid():
                clientform.save()
                return redirect("/client")
            else:
                clientform = ClientForm()
    return render(request, 'clients/edit_client.html', {"form": clientform})

gestion_Stock/gestionCommande/templates/produits/cart.html
  {% extends  "base.html" %}
  {% load static %}
{% block contenu %}
 <div class="row">
		<div class="col-lg-12">
			<div class="box-element">

				<a  class="btn btn-outline-dark" href="{% url 'acceuil' %}">&#x2190; Continue Shopping</a>

				<br>
				<br>
				<table class="table">
					<tr>
						<th><h5>Items: <strong>3</strong></h5></th>
						<th><h5>Total:<strong> $42</strong></h5></th>
						<th>
							<a  style="float:right; margin:5px;" class="btn btn-success" href="{% url 'checkout' %}">Checkout</a>
						</th>
					</tr>
				</table>

			</div>

			<br>
			<div class="box-element">
				<div class="cart-row">
					<div style="flex:2"></div>
					<div style="flex:2"><strong>Item</strong></div>
					<div style="flex:1"><strong>Price</strong></div>
					<div style="flex:1"><strong>Quantity</strong></div>
					<div style="flex:1"><strong>Total</strong></div>
				</div>

				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{% static 'images/placeholder.png' %}"></div>
					<div style="flex:2"><p>Product 1</p></div>
					<div style="flex:1"><p>$20</p></div>
					<div style="flex:1">
						<p class="quantity">2</p>
						<div class="quantity">
							<img class="chg-quantity" src="{% static  'images/arrow-up.png' %}">

							<img class="chg-quantity" src="{% static  'images/arrow-down.png' %}">
						</div>
					</div>
					<div style="flex:1"><p>$32</p></div>
				</div>

			</div>
		</div>
	</div>
{% endblock%}

gestion_Stock/gestionCommande/templates/produits/delete_produit.html
 {% extends  "base.html" %}
{% block contenu %}
 <div class="row mt-2">
     <div class="col-md-6 m-auto">
       <div class="card card-body">
         <form method="post">
             {% csrf_token%}
              <div class="alert alert-danger" role="alert">
                   Etes-vous sur de supprimer {{produit}} ?
              </div>
             <button type="submit" class="btn btn-info"><a href="{% url 'acceuil' %}">NON </a></button>
             <button type="submit" class="btn btn-danger"><span> OUI</span> </button>

         </form>
       </div>
     </div>
 </div>
{% endblock%}

gestion_Stock/gestionCommande/templates/produits/edit_produit.html
  {% extends  "base.html" %}
{% block contenu %}
 <div class="row mt-2">
     <div class="col-md-6 m-auto">
       <div class="card card-body">
         <form method="post" enctype="multipart/form-data">
             {% csrf_token%}
             <div class="form-group">
                <label for="designation">Designation</label>
                <input type="text" class="form-control"  name="designation" value="{{produit.designation}}" aria-describedby="emailHelp">
              </div>
             <div class="form-group">
                <label for="designation">Description</label>
                <input type="text" class="form-control"  name="description" value="{{produit.description}}" aria-describedby="emailHelp">
              </div>
             <div class="form-group">
                <label for="datePerempt">Date peremtion</label>
                <input type="date" class="form-control"  name="datePerempt" value="{{produit.datePerempt}}" aria-describedby="emailHelp">
              </div>
             <div class="form-group">
                <label for="prixU">Prix Unitaire</label>
                <input type="number" class="form-control"  name="prixU" value="{{produit.prixU}}" aria-describedby="emailHelp">
              </div>
             <div class="form-group">
                <label for="quantite">Quantite</label>
                <input type="number" class="form-control"  name="quantite" value="{{produit.quantite}}" aria-describedby="emailHelp">
              </div>

             <div class="form-group">
                <label for="photo">Photo</label>
                <input type="file" class="form-control"  upload_to="images/%Y/%m/%d/"   name="photo" value="{{produit.photo.url}}" aria-describedby="emailHelp">
             </div>


             <button type="submit" class="btn btn-primary"> Modifier </button>

         </form>
       </div>
     </div>
 </div>
{% endblock%}

gestion_Stock/gestionCommande/templates/produits/nouveau_produit.html
 {% extends  "base.html" %}
{% block contenu %}
 <div class="row mt-2">
     <div class="col-md-6 m-auto">
       <div class="card card-body">
         <form method="post" enctype="multipart/form-data" >
             {% csrf_token %}
             <div class="form-group">
                <label for="designation">Designation</label>
                <input type="text" class="form-control"  name="designation" aria-describedby="emailHelp">
              </div>
             <div class="form-group">
                <label for="designation">Description</label>
                <input type="text" class="form-control"  name="description" aria-describedby="emailHelp">
              </div>
             <div class="form-group">
                <label for="datePerempt">Date peremtion</label>
                <input type="date" class="form-control"  name="datePerempt" aria-describedby="emailHelp">
              </div>
             <div class="form-group">
                <label for="prixU">Prix Unitaire</label>
                <input type="number" class="form-control"  name="prixU" aria-describedby="emailHelp">
              </div>
             <div class="form-group">
                <label for="quantite">Quantite</label>
                <input type="number" class="form-control"  name="quantite" aria-describedby="emailHelp">
              </div>

             <div class="form-group">
                <label for="photo">Photo</label>
                <input type="file" class="form-control"  upload_to='images/%Y/%m/%d/' name="photo" aria-describedby="emailHelp">
              </div>

             <div class='form-group selectpicker multiple data-selected-text-format '>
                  <label for="categories">Categorie</label>
             </br>
                  <select name="categorie" required id="id_categorie" class="form-control >
                      {% for categorie in categories %}

                       <option value="{{categorie.designation}}" >{{categorie.designation}}</option>
                       {% endfor %}



                  </select>

              </div>

             <button type='submit' class='btn btn-primary'>Enregistrer</button>

         </form>
       </div>
     </div>
 </div>
{% endblock%}

gestion_Stock/gestionCommande/templates/produits/produit.html
 {% extends  "base.html" %}
{% block contenu %}
  <div class="mt-2">
        <a class="btn btn-info glyphicon glyphicon-plus" href="{% url 'nouveau_produit' %}">Ajouter produit</a>
  </div>

 <div class="row mt-2 mb-2 col-12  ">
     <div class="col-md m-auto">
         <div class="card card-body">
               <div class="panel-heading"><h3  class="display-2">Produits</h3></div>
             {% if produits %}
            <table class=" table table-striped">
                <thead class="thead-dark">
                   <tr>
                      <th scope="col">Designation</th>
                      <th scope="col">Description</th>
                      <th scope="col">DatePeremption</th>
                      <th scope="col">PrixU</th>
                        <th scope="col">Quantite</th>
                   </tr>
                </thead>
               {% for produit in produits %}
                <a href=" {% url 'details' produit.id %}">
                <tr>
                    <!-- on gere dynamiquement les urls ici details est declare dans url name="details"
                     ici on precise l'argument produit.id qui represente l'id du produit -->

                    <td>
                          <a href=" {% url 'details' produit.id %}">
                              <!--filtre | default_if_none : "non renseigne"  -->
                             {{ produit.designation}}
                          </a>
                    </td>
                    <td>
                          <a href=" {% url 'details' produit.id %}">
                        {{ produit.description }}
                          </a>
                    </td>
                    <td>
                          <a href=" {% url 'details' produit.id %}">
                        {{ produit.datePerempt }}
                          </a>
                    </td>
                    <td>
                          <a href=" {% url 'details' produit.id %}">
                        {{produit.prixU}}
                          </a>
                    </td>
                    <td>
                          <a href=" {% url 'details' produit.id %}">
                         {{produit.quantite}}
                          </a>
                    </td>


                </tr>
                </a>
                    {% endfor%}
            </table>
             <!-- affichage par pagination j'utilise pagination.html pour l'affichage -->
          {% include  "partiel/pagination.html" %}
         {% else %}
             <h3>Produit vide</h3>
         {% endif%}
         </div>



     </div>


 </div>
{% endblock%}

gestion_Stock/gestionCommande/templates/produits/produit_detail.html
   {% extends  "base.html" %}
{% block contenu %}

 <div class="row mt-2">
     <div class="col-md-9 m-auto">

         <div class="row">
         <div class="card card-body ">
              <div class="panel-heading"><h3  class="text-center">Detail produit</h3></div>
              <div class="col-md-3  center "  style=' width: 18rem;'>
                          <a href=" {% url 'details' produit.id %}"  class=" center ">
                              <!--filtre | default_if_none : "non renseigne"  -->
                            <img style="position:relative;left:300px;" src="{{  produit.photo.url }}"  class="card-img-top center " alt="Card image cap"  width="350"  height="350">

                              <br/> <br/>  <br/>
                          </a>


           </div>
             <ul class="list-group list-group-flush">
              <li class="list-group-item">Designation : {{produit.designation}}</li>
              <li class="list-group-item">Description : {{produit.description}}</li>
              <li class="list-group-item">Date Peremption : {{produit.datePerempt}}</li>
              <li class="list-group-item">Prix Unitaire : {{produit.prixU}}</li>
              <li class="list-group-item">Quantite : {{produit.quantite}}</li>
            </ul>


             <div class="mt-2">
                <button class="btn btn-info"> <a  href=" {% url 'edit_produit' produit.id %}">Modifier</a></button>
                  <button class="btn btn-danger"> <a  href=" {% url 'delete_produit' produit.id %}">Supprimer</a></button>
             </div>

         </div>

         </div>


     </div>
 </div>
{% endblock%}

gestion_Stock/gestionCommande/templates/produits/search.html
  {% extends  "base.html" %}
{% block contenu %}

 <div class="row">
      <div class="mt-2 col-md-3">
           {% if  categories %}
              <ul class="list-group"  >
                  {% for  categorie in   categories %}

                  <a class="btn btn-info" href=" {% url 'typecategories' categorie.id %}">
                    <button class="btn btn-info">
                      <li   class="list-group-item  btn btn-info">
                            {{categorie.designation}}
                      </li>
                    </button>
                  </a>

                  {% endfor%}
             </ul>
        {% endif %}
     </div>
     <div class="col-9">
  <div class="mt-2">
        <a class="btn btn-info" href="{% url 'nouveau_produit' %}">Ajouter produit</a>
  </div>

     <div class="row mt-2 mb-2 col-12  ">
         <div class="col-md m-auto">
             <div class="card card-body">
                   <div class="panel-heading"><h3  class="display-2">Produits</h3></div>
                  <div class="row">
                 {% if produits %}
                   {% for produit in produits %}

                       <div class="col-md-3 col-3  "  style=' width: 18rem;'>
                              <a href=" {% url 'details' produit.id %}">
                                  <!--filtre | default_if_none : "non renseigne"  -->
                                <img src="{{  produit.photo.url }}"  class="card-img-top border border-info rounded" alt="Card image cap"   height="350">
                                  <span class="btn btn-primary"> {{produit.prixU}} FCFA</span>
                                  <br/> <br/>  <br/>
                              </a>
                       </div>

                      {% endfor%}
                 {% else %}
                 <h3>Produit vide</h3>
                  {% endif%}
                      </div>
             </div>

         </div>
</div>

 </div>
 </div>
{% endblock%}